config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "quizzes#index"

  get 'quiz_submissions/create'
  get 'quiz_submissions/show'
  
  resources :quizzes do
    resources :questions
    resources :quiz_submissions, only: [:show, :create], as: 'submissions'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  validates :correct_answer, inclusion: { in: 1..4 }
  has_one_attached :image
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :questions
  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true

  def correct_answer_text
    send("answer_#{correct_answer}")
  end
end

app/models/quiz_submission.rb
class QuizSubmission < ApplicationRecord
  belongs_to :user
  belongs_to :quiz

  after_initialize :init

  def init
    self.user_answers ||= {}
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  def index
    @questions = Question.all
  end

  def show; end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.save ? (redirect_to question_url(@question)) : (render :new)
  end

  def update
    @question.update(question_params) ? (redirect_to question_url(@question)) : (render :edit)
  end

  def destroy
    @question.destroy
    redirect_to questions_url
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(
      :quiz_id,
      :content,
      :answer_1,
      :answer_2,
      :answer_3,
      :answer_4,
      :correct_answer
    )
  end
end

app/controllers/quiz_submissions_controller.rb
class QuizSubmissionsController < ApplicationController
  before_action :find_quiz_submission, only: [:show]

  def show
    @quiz = @quiz_submission.quiz
  end

  def create
    @quiz = Quiz.find(params[:quiz_id])

    user_answers = {}
    correct_answers = 0

    params.each do |key, value|
      next unless key.start_with?('question_')

      question_id = key.split('_').last.to_i
      selected_answer = value.to_i
      user_answers[question_id.to_s] = selected_answer
      question = Question.find(question_id)

      correct_answers += 1 if question.correct_answer == selected_answer
    end

    score = (correct_answers.to_f / @quiz.questions.count) * 100
    @quiz_submission = QuizSubmission.create(quiz: @quiz, user: current_user, score:, user_answers:)

    redirect_to quiz_submission_path(@quiz, @quiz_submission)
  end

  private

  def find_quiz_submission
    @quiz_submission = QuizSubmission.find(params[:id])
  end

  def quiz_submission_params
    params.require(:quiz_submission).permit(
      :quiz_id,
      :user_id,
      :score,
      user_answers: {}
    )
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy ]

  def index
    @quizzes = Quiz.all
  end

  def show; end

  def new
    @quiz = Quiz.new
    @quiz.questions.build
  end

  def edit; end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.save ? (redirect_to quiz_url(@quiz)) : (render :new)
  end

  def update
    @quiz.update(quiz_params) ? (redirect_to quiz_url(@quiz)) : (render :edit)
  end

  def destroy
    @quiz.destroy
    redirect_to quizzes_url
  end

  private

  def set_quiz
    @quiz = Quiz.find(params[:id])
  end

  def quiz_params
    params.require(:quiz).permit(
      :title,
      :image,
      questions_attributes: [
        :id,
        :_destroy,
        :content,
        :answer_1,
        :answer_2,
        :answer_3,
        :answer_4,
        :correct_answer,
        :image
      ]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_submissions_helper.rb
module QuizSubmissionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand me-5" href="/">Quiz</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse ms-5" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=  %>"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=  %>"></a>
        </li>
      </ul>
      <% if user_signed_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <span class="badge badge-success float-right mr-5">
              <a class="nav-link" href="<%= edit_user_registration_path %>"><%= current_user.email %></a>
            </span>
          </li>
        </ul>

        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path, class: "btn btn-success me-3" %>
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>

    <main class="container my-5 pb-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :quiz %>
    <%= f.input :content %>
    <%= f.input :image, as: :file, input_html: {} %>
    <%= f.input :answer_1 %>
    <%= f.input :answer_2 %>
    <%= f.input :answer_3 %>
    <%= f.input :answer_4 %>
    <%= f.input :correct_answer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <p>
    <strong>Quiz:</strong>
    <%= question.quiz_id %>
  </p>

  <% if question.image.attached? %>
    <%= image_tag question.image, class: 'img-fluid' %>
  <% end %>

  <p>
    <strong>Content:</strong>
    <%= question.content %>
  </p>

  <p>
    <strong>Answer 1:</strong>
    <%= question.answer_1 %>
  </p>

  <p>
    <strong>Answer 2:</strong>
    <%= question.answer_2 %>
  </p>

  <p>
    <strong>Answer 3:</strong>
    <%= question.answer_3 %>
  </p>

  <p>
    <strong>Answer 4:</strong>
    <%= question.answer_4 %>
  </p>

  <p>
    <strong>Correct answer:</strong>
    <%= question.correct_answer %>
  </p>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>
<div class="btn-group my-5">
  <%= link_to "Show this question", @question, class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to questions", questions_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/questions/index.html.erb
<h1>Questions</h1>

<% @questions.each do |question| %>
  <%= render question %>
  <p><%= link_to "Show this question", question, class: "btn btn-sm btn-outline-dark" %></p>
<% end %>

<%= link_to "New question", new_question_path, class: "btn btn-sm btn-outline-dark" %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render "form", question: @question %>

<br>
<div>
  <%= link_to "Back to questions", questions_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/questions/show.html.erb
<%= render @question %>

<div class="btn-group my-5">
  <%= link_to "Edit this question", edit_question_path(@question), class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to questions", questions_path, class: "btn btn-sm btn-outline-dark" %>
  <%= button_to "Destroy this question", @question, method: :delete, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/quiz_submissions/create.html.erb
<h1>QuizSubmissions#create</h1>
<p>Find me in app/views/quiz_submissions/create.html.erb</p>

app/views/quiz_submissions/show.html.erb
<h2>Your Quiz Score: <%= @quiz_submission.score.round(2) %>%</h2>

<% @quiz.questions.each do |question| %>
  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">Question:</h5>
      <p class="card-text"><%= question.content %></p>

      <% if question.image.attached? %>
        <%= image_tag question.image, class: "img-fluid mb-3" %>
      <% end %>

      <% 1.upto(4) do |answer_index| %>
        <% selected_answer = @quiz_submission.user_answers[question.id.to_s].to_i %>
        <div class="form-check">
          <% if answer_index == question.correct_answer %>
            <div class="alert alert-success">
              <strong>Correct answer: </strong> <%= question.send("answer_#{answer_index}") %>
            </div>
          <% elsif answer_index == selected_answer %>
            <div class="alert alert-danger">
              <strong>Your incorrect answer: </strong> <%= question.send("answer_#{answer_index}") %>
            </div>
          <% else %>
            <div class="alert alert-secondary">
              <%= question.send("answer_#{answer_index}") %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true, data: {
  controller: "nested-form", nested_form_wrapper_selector_value: ".nested-form-wrapper"
  }) do |form| %>

  <template data-nested-form-target="template">
    <%= form.fields_for :questions, Question.new, child_index: "NEW_RECORD" do |question_fields| %>
      <%= render "question_fields", f: question_fields %>
    <% end %>
  </template>

  <%= form.fields_for :questions do |question_fields| %>
    <%= render "question_fields", f: question_fields %>
  <% end %>

  <div data-nested-form-target="target"></div>
  <button type="button" data-action="nested-form#add" class="btn btn-success mb-3">Add Question</button>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/quizzes/_question_fields.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="card mb-4">
    <div class="card-body">
      <%= f.label :content, "Question" %>
      <%= f.text_area :content, class: "form-control mb-3" %>
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control mb-3" %>

      <% 1.upto(4) do |answer_index| %>
        <%= f.label "answer_#{answer_index}", "Answer #{answer_index}" %>
        <%= f.text_field "answer_#{answer_index}", class: "form-control mb-3" %>
      <% end %>

      <%= f.label :correct_answer, "Correct Answer" %>
      <%= f.select :correct_answer, (1..4).to_a, {}, class: "form-control mb-3" %>
      
      <button type="button" data-action="nested-form#remove" class="btn btn-danger">Remove Question</button>
      <%= f.hidden_field :_destroy %>
    </div>
  </div>
</div>

app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>">
  <p>
    <strong>Title:</strong>
    <%= quiz.title %>
  </p>
</div>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render "form", quiz: @quiz %>

<br>
<div class="btn-group my-5">
  <%= link_to "Show this quiz", @quiz, class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to quizzes", quizzes_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/quizzes/index.html.erb
<h1>Quizzes</h1>

<% @quizzes.each do |quiz| %>
  <%= render quiz %>
  <p><%= link_to "Show this quiz", quiz, class: "btn btn-sm btn-outline-dark" %></p>
<% end %>

<%= link_to "New quiz", new_quiz_path, class: "btn btn-sm btn-outline-dark" %>

app/views/quizzes/new.html.erb
<h1 class="mb-5">
  New quiz
</h1>

<%= render "form", quiz: @quiz %>

<br>
<div>
  <%= link_to "Back to quizzes", quizzes_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/quizzes/show.html.erb
<%= form_with(url: quiz_submissions_path(@quiz), local: true, method: :post) do |form| %>
  <% @quiz.questions.each_with_index do |question, index| %>
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">Question <%= index + 1 %>:</h5>
        <p class="card-text"><%= question.content %></p>

        <% if question.image.attached? %>
          <%= image_tag question.image, class: "img-fluid mb-3" %>
        <% end %>

        <% 1.upto(4) do |answer_index| %>
          <div class="form-check">
            <%= form.radio_button "question_#{question.id}", answer_index, class: "form-check-input" %>
            <%= form.label "question_#{question.id}_#{answer_index}", question.send("answer_#{answer_index}"), class: "form-check-label" %>
          </div>
        <% end %>

      </div>
    </div>
  <% end %>

  <div class="text-center">
    <%= form.submit "Submit Quiz", class: "btn btn-primary" %>
  </div>
<% end %>

<div class="btn-group my-5">
  <%= link_to "Edit this quiz", edit_quiz_path(@quiz), class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to quizzes", quizzes_path, class: "btn btn-sm btn-outline-dark" %>
  <%= button_to "Destroy this quiz", @quiz, method: :delete, class: "btn btn-sm btn-outline-dark" %>
</div>